# Key settings (must edit)
project_title: choochoo test JOSE
project_repo: lucydot/choochoo-test-JOSE
admins:
- lucydot
instructors:
- lucydot
students:
- lucydot
web_address: https://lucydot.github.io/choochoo-test-JOSE

# User options (may edit)
questions: true
votes_required: 3
gh-pages: true



